# Generated by Django 5.1.3 on 2024-12-04 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='variants',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.color'),
        ),
    ]
