# Generated by Django 5.1.3 on 2024-12-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_variants_color_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variants',
            old_name='products',
            new_name='product_variant',
        ),
    ]
